export default {
    TOOGLE_NAVIGATION: "TOOGLE_NAVIGATION",
    BREADCRUMB_PATH: "BREADCRUMB_PATH",
    TOGGLE_CART: "TOGGLE_CART",

    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    UPDATE_CART: "UPDATE_CART"
};